language: d

d:
  - dmd-2.071.1
  - ldc-1.0.0

install:
  - wget -c ftp://ftp.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP1250.TXT

script:
  - dub test --compiler=${DC} -- CP1250.TXT

branches:
  only:
    - master

notifications:
  email: true

sudo: false

matrix:
  exclude:
    
